before_all do
    ensure_git_branch(
        branch: 'master'
    )
    ensure_git_status_clean
    git_pull
end

platform :android do 
    #Android Lanes
    desc 'Generate Android APK.'
    private_lane :build do
        gradle(task: 'clean', project_dir: 'android/')
        gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/')
    end

    desc 'Upload APK on Play Store.'
        lane :beta do
        build
        supply(track: 'beta', track_promote_to: 'beta')
        git_commit(path: ['./android/gradle.properties'], message: 'Upload versionCode')
        push_to_git_remote
    end
end