before_all do
    ensure_git_branch(
        branch: 'master'
    )
    ensure_git_status_clean
    git_pull
end

platform :ios do 
    #iOS Lanes
end

platform :android do 
    #Android Lanes
    desc 'Generate Android APK.'
    private_lane :build do
        increment_build_number(
            #build_number: "75" # set a specific number
        ) # automatically increment by one
        gradle(task: 'clean', project_dir: 'android/')
        # gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/') #apk
        gradle(task: 'bundle', build_type: 'Release', project_dir: 'android/') #apk
    end
    lane :playstore do
        # gradle(
        #   task: 'assemble',
        #   build_type: 'Release'
        # )
        gradle(
            task: "clean assembleRelease", 
            project_dir: 'android/'
            )
        gradle(
            task: 'bundle', 
            build_type: 'Release',
             project_dir: 'android/',
            #  properties: {
            #     "android.injected.signing.store.file" => "loca_file_system/unsigloenguerra.jks",
            #     "android.injected.signing.store.password" => "Un$1986nWa_",
            #     "android.injected.signing.key.alias" => "key0",
            #     "android.injected.signing.key.password" => "Un$1986nWa_",
            #   }
             )
        upload_to_play_store(
            track: 'rollout', #production
            rollout: '0.5',
            skip_upload_metadata: true,
            skip_upload_images: true,
            skip_upload_screenshots: true
            
        ) # Uploads the APK built in the gradle step above and releases it to all production users
    end

    desc 'Upload APK on Play Store.'
        lane :beta do
        build
        supply(track: 'beta', track_promote_to: 'beta')
        git_commit(path: ['./android/gradle.properties'], message: 'Upload versionCode')
        push_to_git_remote
    end

    desc 'Ship to Playstore Beta.'
        lane :beta2 do
        build
        supply(track: 'beta', track_promote_to: 'beta')
        git_commit(path: ['./android/gradle.properties'], message: 'Bump versionCode')
        push_to_git_remote
    end
end